/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Joaquim Monteiro
 */
public class Tipo_Pedido extends javax.swing.JFrame {

    /**
     * Creates new form Tipo_Pedido
     */
    public Tipo_Pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personalizado = new javax.swing.JButton();
        normal = new javax.swing.JButton();
        voltar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personalizado.setBackground(new java.awt.Color(0, 0, 0));
        personalizado.setFont(new java.awt.Font("Ravie", 0, 20)); // NOI18N
        personalizado.setForeground(new java.awt.Color(255, 204, 102));
        personalizado.setText("Fazer Pedido Personalizado");
        personalizado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        personalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalizadoActionPerformed(evt);
            }
        });
        getContentPane().add(personalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 397, 41));

        normal.setBackground(new java.awt.Color(0, 0, 0));
        normal.setFont(new java.awt.Font("Ravie", 3, 18)); // NOI18N
        normal.setForeground(new java.awt.Color(255, 204, 102));
        normal.setText("Fazer Pedido Normal");
        normal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });
        getContentPane().add(normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 400, 40));

        voltar1.setFont(new java.awt.Font("Ravie", 3, 14)); // NOI18N
        voltar1.setText("voltar");
        voltar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(voltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 413, 100, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Ravie", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 102));
        jLabel2.setText("My Food");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 150, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vv.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
        Pedido_normal pedido_n = new Pedido_normal();
        pedido_n.setVisible(true);
        dispose();
    }//GEN-LAST:event_normalActionPerformed

    private void voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar1ActionPerformed
        SoftwareMyFood myfood = new SoftwareMyFood();
        myfood.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltar1ActionPerformed

    private void personalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalizadoActionPerformed
        Pedido_personalizado pedido_p = new Pedido_personalizado();
        pedido_p.setVisible(true);
        dispose();
    }//GEN-LAST:event_personalizadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tipo_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tipo_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tipo_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tipo_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tipo_Pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton normal;
    private javax.swing.JButton personalizado;
    private javax.swing.JButton voltar1;
    // End of variables declaration//GEN-END:variables
}
